import type { Metadata, Viewport } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers/providers";
import { auth } from "@/auth";

const montserrat = Montserrat({
    variable: "--font-montserrat-sans",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth()

    return (
        <html
            lang="en"
            className={`${montserrat.variable} ${inter.variable} h-full antialiased scrollbar-gutter-stable`}
        >
            <body className="min-h-full flex flex-col">
                <Providers session={session}>{children}</Providers>
            </body>
        </html>
    );
}
